# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftI5NXRGiMHjGq6sYiKyUev4DBm4j50K
"""

import pandas as pd

s1 = pd.Series([1,2,3,4,5])

s1

#Change series index
s1 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s1

#creating Series using Dictionary
pd.Series({'a':10,'b':20,'c':0})

#Extracting Individual Elements
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[4]

s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[-4:]

s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[4:]

#adding scaler value to the series 
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1+5

s1=pd.Series([1,2,3,4,5,6,7,8,9])
s2=pd.Series([10,20,30,40,50,60,70,80,90])
s1+s2

#Dataframe of 2 dimensional Data
import pandas as pd
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

